### PR TITLE
Fix naming convention for deleting media

### PR DESCRIPTION
**Pull request by ghost**
Fixed the added checkbox field name (using camelCase instead of a em dash)
The em dash caused malfunction when we tried to render field like this : 

``` twig
{{ form_widget(del-image) }}
```

### CODE REVIEW

**Comment by ghost** [comment]
Any news about this PR ?

**Comment by choomz** [comment]
Hi,

I'll try to merge it asap (need to refactor some failing tests because of namespaces ..).
Can you please update your changes every where (in the deleting media doc) ?

This PR will be merged when i'll tag a new version as it introduce a little BC (if users already have a del-image in their controllers, it will break after the merge).

This new version will come asap, it will introduce some additional features and i'll merge at this moment.

**Comment by ghost** [comment]
Updated for SF2.3

**Comment by choomz** [comment]
Thanks ! Sorry for the late merge ..

**Pull request merged**
