### PR TITLE
Image filters

### PR DESCRIPTION
**Pull request by jcrombez**
New behavior for the "resize" filter and previous behavior renamed "crop".

### CODE REVIEW

**Comment by ghost** [comment]
Hi, good job  :D,  why don't merge with master branch ?

**Comment by jcrombez** [comment]
Because it's not backward compatible, those features are planned to be integrated in the master but later and with a different implementation. To avoid too many BC updates, this implementation is not merged.

**Comment by choomz** [comment]
Yes Jeremy is right.

The aim is to provide a 1.1 version with BC breaks on twig filter API.

I want to refactor a bit the way to go with the ablity to provide filter trought the Symfony compiler pass.
So anyone can implement a filter on a media.

I'll try to work on it asap, so actually the feature will stay on this branch, and will be merge on master after the twig filter behavior is stable and tested, and with and upgrade file.

**Comment by choomz** [comment]
Just for your information, i updated a little bit your code, in order to manage same medias with different filters.
There was a path colision because of the removal of the subfolder in the cache hierarchy.

Note that with the tests on filters name, currently passing other options to media temlate don't work (for exemple 'title' : 'foo' in third array parameter).

I'll fix that on next update.

**Comment by ghost** [comment]
Since this update nothing works properly :/

**Comment by jcrombez** [comment]
Could you be more specific ?

**Comment by choomz** [comment]
Well, if you're trying to render your views and gets an exception, juste delete your image cache and refresh your page.

This is due to the fix of path collisions.

And please, create new issues now for bugs :)

**Pull request merged**
